# Generated by Django 2.1.4 on 2018-12-16 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.TextField(max_length=3, primary_key=True, serialize=False)),
                ('longname', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='invoiceHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoicePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Currency')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.invoiceHead')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('close_against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ClosingLedger')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('default_ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Ledger')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Ledger'),
        ),
        migrations.AddField(
            model_name='invoicehead',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Vendor'),
        ),
    ]
