# Generated by Django 2.1.4 on 2018-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20181216_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceposition',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
