# Generated by Django 2.1.4 on 2018-12-16 20:19

from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20181216_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='ledger_type',
            field=models.CharField(choices=[(finance.models.LedgerTypes('opening balance'), 'opening balance'), (finance.models.LedgerTypes('active account'), 'active account'), (finance.models.LedgerTypes('passive account'), 'passive account'), (finance.models.LedgerTypes('expense account'), 'expense account'), (finance.models.LedgerTypes('income account'), 'income account'), (finance.models.LedgerTypes('closing balance'), 'closing balance'), (finance.models.LedgerTypes('income statement'), 'income statement')], default='AA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger',
            name='positiveLeft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicehead',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Vendor'),
        ),
        migrations.AlterField(
            model_name='invoiceposition',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invoiceposition',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceItems', to='finance.Ledger'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='close_against',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Ledger'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='default_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Ledger'),
        ),
        migrations.DeleteModel(
            name='ClosingLedger',
        ),
    ]
