# Generated by Django 2.1.4 on 2018-12-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20181216_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='positiveLeft',
        ),
        migrations.AddField(
            model_name='ledger',
            name='close_side',
            field=models.CharField(choices=[('L', 'left side'), ('R', 'right side')], default='L', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ledger_type',
            field=models.CharField(choices=[('OB', 'opening balance'), ('AA', 'active account'), ('PA', 'passive account'), ('EA', 'expense account'), ('IA', 'income account'), ('CB', 'closing balance'), ('IS', 'income statement')], max_length=2),
        ),
    ]
