# Generated by Django 2.1.4 on 2018-12-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20181216_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('changed_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('changed_on', models.DateTimeField(auto_now=True)),
                ('groupName', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('changed_on', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportedLanguage',
            fields=[
                ('created_on', models.DateTimeField(auto_now=True)),
                ('changed_on', models.DateTimeField(auto_now=True)),
                ('short', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('long', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='lineText',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoicehead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='invoicehead',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoicehead',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Vendor'),
        ),
        migrations.AlterField(
            model_name='invoiceposition',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='finance.InvoiceHead'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='close_side',
            field=models.CharField(choices=[('L', 'left side'), ('R', 'right side'), ('N', 'none')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ledger_type',
            field=models.CharField(choices=[('OB', 'opening balance'), ('AA', 'active account'), ('PA', 'passive account'), ('EA', 'expense account'), ('IA', 'income account'), ('CB', 'closing balance'), ('IS', 'income statement'), ('XX', 'none')], max_length=2),
        ),
        migrations.AddField(
            model_name='materialtext',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.SupportedLanguage'),
        ),
        migrations.AddField(
            model_name='material',
            name='group',
            field=models.ManyToManyField(blank=True, to='finance.MaterialGroup'),
        ),
        migrations.AddField(
            model_name='material',
            name='texts',
            field=models.ManyToManyField(blank=True, to='finance.MaterialText'),
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='materialGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.MaterialGroup'),
        ),
    ]
