# Generated by Django 2.1.4 on 2018-12-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20181216_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicehead',
            name='ocrText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicehead',
            name='tryOCR',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoiceposition',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='finance.InvoiceHead'),
        ),
    ]
