# Generated by Django 2.1.4 on 2018-12-16 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20181216_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceposition',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Material'),
        ),
        migrations.AlterField(
            model_name='invoiceposition',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='finance.InvoiceHead'),
        ),
    ]
