# Generated by Django 2.1.4 on 2018-12-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20181216_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='short_name',
            field=models.TextField(default='<<UNKNOWN>', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceposition',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='finance.InvoiceHead'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
