# Generated by Django 2.1.4 on 2018-12-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20181217_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceposition',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='finance.InvoiceHead'),
        ),
        migrations.AlterField(
            model_name='invoiceposition',
            name='materialGroup',
            field=models.ManyToManyField(blank=True, to='finance.MaterialGroup'),
        ),
    ]
