# Generated by Django 2.1.9 on 2019-06-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20181220_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceposition',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='finance.InvoiceHead'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='close_against',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Ledger'),
        ),
    ]
